export const vendorPayAppsPaymentStatus: any = {
	Draft: 'Draft',
	SubmittedWaitingForOtherParty: "Submitted & Waiting Other Party",
	PaymentAuthorized: "Payment Authorized",
	AutoGeneratedWaitingForBothParties: "Auto Generated & Waiting Both Parties",
	PaymentSent: "Payment Sent",
	PaymentReceived: "Payment Received",
	Rejected: "Rejected",
	AwaitingAcceptance: "Awaiting Acceptance",
};

export const vendorPayAppsResponseStatus: any = {
	Draft: 'Draft',
	AwaitingAcceptance: "Awaiting Acceptance",
	Rejected: "Rejected",
	1: "Submitted & Waiting Other Party",
	2: "Revise & Resubmit",
	3: "Payment Authorized",
	4: "Auto Generated & Waiting Both Parties",
	5: "Payment Sent",
	6: "Payment Received",
};
export const vendorPayAppsPaymentStatusIcons: any = {
	Draft: 'common-icon-Draft',
	SubmittedWaitingForOtherParty: "common-icon-submitted-waiting-party",
	PaymentAuthorized: "common-icon-payment-authorized1",
	AutoGeneratedWaitingForBothParties: "common-icon-auto-generated",
	Rejected: "common-icon-reviewed-decline",
	PaymentSent: "common-icon-payment-sent",
	PaymentReceived: "common-icon-payment-received",
	AwaitingAcceptance: "common-icon-bid-pending-icon"
};
export const vendorPayAppsPaymentStatusColors: any = {
	Draft: '#323232',
	SubmittedWaitingForOtherParty: "#2b8cbd",
	PaymentAuthorized: "#3cbe4b",
	AutoGeneratedWaitingForBothParties: "#c09e2b",
	Rejected: "red",
	PaymentSent: "#37bb6e",
	PaymentReceived: "#37bb6e",
	AwaitingAcceptance: "#c09e2b",
};

export const vendorPayAppsPaymentStatusOptions = [
	{name: 'Draft', text: 'Draft', value: 'Draft', key: 'Draft', id: 'Draft', icon: 'common-icon-Draft', color: "323232", bgColor: "#323232", iconType: 'class'},
	{name: 'Submitted & Waiting Other Party', text: 'Submitted & Waiting Other Party', value: 'SubmittedWaitingForOtherParty', key: 'SubmittedWaitingForOtherParty', id: 'SubmittedWaitingForOtherParty', icon: 'common-icon-submitted-waiting-party', color: "168cc0", bgColor: "#168cc0", iconType: 'class'},
	{name: 'Awaiting Acceptance', text: 'Awaiting Acceptance', value: 'AwaitingAcceptance', key: 'AwaitingAcceptance', id: 'AwaitingAcceptance', icon: 'common-icon-bid-pending-icon', color: "c29e0a", bgColor: "#c29e0a", iconType: 'class'},
	{name: 'Payment Authorized', text: 'Payment Authorized', value: 'PaymentAuthorized', key: 'PaymentAuthorized', id: 'PaymentAuthorized', icon: 'common-icon-payment-authorized1', color: "3cbe4b", bgColor: "#3cbe4b", iconType: 'class'},
	{name: 'Auto Generated & Waiting Both Parties', text: 'Auto Generated & Waiting Both Parties', value: 'AutoGeneratedWaitingForBothParties', key: 'AutoGeneratedWaitingForBothParties', id: 'AutoGeneratedWaitingForBothParties', icon: 'common-icon-auto-generated', color: "c09e2b", bgColor: "#c09e2b", iconType: 'class'},
	{name: 'Payment Sent', text: 'Payment Sent', value: 'PaymentSent', key: 'PaymentSent', id: 'PaymentSent', icon: 'common-icon-payment-sent', color: "05bc68", bgColor: "#05bc68", iconType: 'class'},
	{name: 'Payment Received', text: 'Payment Received', value: 'PaymentReceived', key: 'PaymentReceived', id: 'PaymentReceived', icon: 'common-icon-payment-received', color: "05bc68", bgColor: "#05bc68", iconType: 'class'},
	{name: 'Rejected', text: 'Rejected', value: 'Rejected', key: 'Rejected', id: 'Rejected', icon: 'common-icon-reviewed-decline', color: "ff0000", bgColor: "#ff0000", iconType: 'class'}
];

export const vendorPayAppsPaymentStatusFilterOptions = [{text: 'Draft', id: 'Draft', key: 'Draft', value: 'Draft', icon: 'common-icon-Draft', color: "323232", iconType: 'class'},
{text: 'Submitted & Waiting Other Party', id: 'SubmittedWaitingForOtherParty', key: 'SubmittedWaitingForOtherParty', value: 'SubmittedWaitingForOtherParty', icon: 'ReadyToPostColor', color: "168cc0", iconType: 'class'},
{text: 'Awaiting Acceptance', id: 'AwaitingAcceptance', icon: 'DraftColor', key: 'AwaitingAcceptance', value: 'AwaitingAcceptance', color: "c29e0a", iconType: 'class'},
{text: 'Payment Authorized', id: 'PaymentAuthorized', key: 'PaymentAuthorized', value: 'PaymentAuthorized', icon: 'common-icon-payment-authorized1', color: "17c03f", iconType: 'class'},
{text: 'Auto Generated & Waiting Both Parties', id: 'AutoGeneratedWaitingForBothParties', key: 'AutoGeneratedWaitingForBothParties', value: 'AutoGeneratedWaitingForBothParties', icon: 'common-icon-auto-generated', color: "323232", iconType: 'class'},
{text: 'Payment Sent', id: 'PaymentSent', key: 'PaymentSent', value: 'PaymentSent', icon: 'common-icon-payment-sent', color: "05bc68", iconType: 'class'},
{text: 'Payment Received', id: 'PaymentReceived', key: 'PaymentReceived', value: 'PaymentReceived', icon: 'common-icon-payment-received', color: "05bc68", iconType: 'class'},
{text: 'Rejected', id: 'Rejected', key: 'Rejected', value: 'Rejected', icon: 'common-icon-reviewed-decline', color: "ff0000", iconType: 'class'},

];

export const vendorPayAppsResponseStatusOptions = [{name: 'Draft', id: 'Draft', icon: 'common-icon-Draft', color: "323232", iconType: 'class'},
{name: 'Submitted & Waiting Other Party', id: 'SubmittedWaitingForOtherParty', icon: 'ReadyToPostColor', color: "168cc0", iconType: 'class'},
{name: 'Revise & Resubmit', id: 'Revise', icon: 'DraftColor', color: "168cc0", iconType: 'class'},
{name: 'Payment Authorized', id: 'PaymentAuthorized', icon: 'common-icon-payment-authorized1', color: "17c03f", iconType: 'class'},
{name: 'Auto Generated & Waiting Both Parties', id: 'AutoGeneratedWaitingForBothParties', icon: 'common-icon-auto-generated', color: "323232", iconType: 'class'},
{name: 'Payment Sent', id: 'PaymentSent', icon: 'common-icon-payment-sent', color: "05bc68", iconType: 'class'},
{name: 'Payment Received', id: 'PaymentReceived', icon: 'common-icon-payment-received', color: "05bc68", iconType: 'class'},

];

export const vendorPayStatus: any = {
	'Draft': {icon: 'common-icon-Draft', text: 'Draft', color: '#323232', lightColor: '#dfdfdf'},
	'SubmittedWaitingForOtherParty': {icon: 'common-icon-payment-authorized', text: 'Submitted & Waiting Other Party', color: '#2b8cbd', lightColor: '#ddeef5'},
	'ReviseResubmit': {icon: 'common-icon-revise-resubmit', text: 'Revise & Resubmit', color: '#31b0bc', lightColor: '#caeef2'},
	'PaymentAuthorized': {icon: 'common-icon-payment-authorized1', text: 'Payment Authorized', color: '#3cbe4b', lightColor: '#ebfaeb'},
	'AutoGeneratedWaitingForBothParties': {icon: 'common-icon-auto-generated', text: 'Auto Generated & waiting both Parties', color: '#c09e2b', lightColor: '#f7f1dc'},
	'PaymentReceived': {icon: 'common-icon-payment-received', text: 'Payment Received', color: '#37bb6e', lightColor: '#bff3d5'},
	'AwaitingAcceptance': {icon: 'common-icon-bid-pending-icon', text: 'Awaiting Acceptance', color: '#c09e2b', lightColor: '#f7f1dc'},
	'Rejected': {icon: 'common-icon-reviewed-decline', text: 'Rejected', color: '#d34441', lightColor: '#f9e2e2'},
	'PaymentSent': {icon: 'common-icon-payment-sent', text: 'Payment Sent', color: '#37bb6e', lightColor: '#bff3d5'}
};