import { createAsyncThunk, createSlice } from "@reduxjs/toolkit";
import { fetchGroupedBarChartData } from "./groupedBarChartAPI";

export type AnalyticalTabPageTypes = "groupedbarchart" | "chart";

export interface AnalyticalTabState {
  loadingGroupedbarchart: boolean;
  groupedbarcharts: any[];
}

const initialState: AnalyticalTabState = {
  loadingGroupedbarchart: false,
  groupedbarcharts: [],
};

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const fetchGroupedbarcharts = createAsyncThunk(
  "groupedbarchart/Chart",
  async () => {
    const groupedbarcharts = await fetchGroupedBarChartData();

    // The value we return becomes the `fulfilled` action payload
    return groupedbarcharts;
  }
);

export const groupedbarchartSlice = createSlice({
  name: "groupedBarChart",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    //
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(fetchGroupedbarcharts.pending, (state) => {
        state.loadingGroupedbarchart = true;
      })
      .addCase(fetchGroupedbarcharts.fulfilled, (state, action) => {
        state.loadingGroupedbarchart = false;
        state.groupedbarcharts = action.payload;
      })
      .addCase(fetchGroupedbarcharts.rejected, (state, action) => {
        state.loadingGroupedbarchart = false;
      });
  },
});

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
// export const getPageType = (state: RootState) => state.inventoryCategory;

// We can also write thunks by hand, which may contain both sync and async logic.
// Here's an example of conditionally dispatching actions based on current state.

export default groupedbarchartSlice.reducer;
