import { createAsyncThunk, createSlice } from "@reduxjs/toolkit";
import { fetchInventoryManufacturerList } from "./inventoryManufacturerAPI";

export type ToolsAndEquipmentPageTypes = "manufacturer" | "inventory";

export interface ToolsAndEquipmentState {
  loadingManufacturer: boolean;
  inventoryManufacturers: any[];
}

const initialState: ToolsAndEquipmentState = {
  loadingManufacturer: false,
  inventoryManufacturers: [],
};

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const fetchManufacturers = createAsyncThunk(
  "inventory/Manufacturers",
  async () => {
    const inventoryManufacturer = await fetchInventoryManufacturerList();

    // The value we return becomes the `fulfilled` action payload
    return inventoryManufacturer;
  }
);

export const inventoryManufacturerSlice = createSlice({
  name: "inventoryManufacturer",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    //
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(fetchManufacturers.pending, (state) => {
        state.loadingManufacturer = true;
      })
      .addCase(fetchManufacturers.fulfilled, (state, action) => {
        state.loadingManufacturer = false;
        state.inventoryManufacturers = action.payload;
      })
      .addCase(fetchManufacturers.rejected, (state, action) => {
        state.loadingManufacturer = false;
      });
  },
});

// export const { getAll } = subcategorySlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
// export const getPageType = (state: RootState) => state.inventoryManufacturer;



export default inventoryManufacturerSlice.reducer;
