import { createAsyncThunk, createSlice, PayloadAction } from '@reduxjs/toolkit';
import { RootState, AppThunk } from 'app/store';
import { fetchCatalogList } from './catalogAPI';

export type ToolsAndEquipmentPageTypes = 'catalog' | 'inventory';

export interface ToolsAndEquipmentState {
	page: ToolsAndEquipmentPageTypes;
	loading: boolean;
	catalogs: any[];
}

const initialState: ToolsAndEquipmentState = {
	page: 'catalog',
	loading: false,
	catalogs: []
};

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const fetchCatalogs = createAsyncThunk(
	'catalog/getAll',
	async () => {
		const catalogs = await fetchCatalogList();
		// The value we return becomes the `fulfilled` action payload
		return catalogs;
	}
);

export const catalogSlice = createSlice({
	name: 'catalog',
	initialState,
	// The `reducers` field lets us define reducers and generate associated actions
	reducers: {
		setPageType: (state, action: PayloadAction<ToolsAndEquipmentPageTypes>) => {
			// return { ...state, ...{ page: action.payload } };
			state.page = action.payload;
		},
		addCatalog: (state) => {
			// Redux Toolkit allows us to write "mutating" logic in reducers. It
			// doesn't actually mutate the state because it uses the Immer library,
			// which detects changes to a "draft state" and produces a brand new
			// immutable state based off those changes
			// state.value += 1;
		},
		updateCatalog: (state) => {
			// state.value -= 1;
		},
		// Use the PayloadAction type to declare the contents of `action.payload`
		deleteCatalog: (state, action: PayloadAction<any>) => {
			// state.value += action.payload;
		},
	},
	// The `extraReducers` field lets the slice handle actions defined elsewhere,
	// including actions generated by createAsyncThunk or in other slices.
	extraReducers: (builder) => {
		builder
			.addCase(fetchCatalogs.pending, (state) => {
				state.loading = true;
			})
			.addCase(fetchCatalogs.fulfilled, (state, action) => {
				state.loading = false;
				state.catalogs = action.payload;
			})
			.addCase(fetchCatalogs.rejected, (state) => {
				state.loading = false;
			});
	}
});

export const { setPageType, addCatalog, updateCatalog, deleteCatalog } = catalogSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const getPageType = (state: RootState) => state.catalog.page;

// We can also write thunks by hand, which may contain both sync and async logic.
// Here's an example of conditionally dispatching actions based on current state.
// export const incrementIfOdd =
// 	(amount: number): AppThunk =>
// 		(dispatch, getState) => {
// 			const currentValue = selectCount(getState());
// 			if (currentValue % 2 === 1) {
// 				dispatch(incrementByAmount(amount));
// 			}
// 		};

export default catalogSlice.reducer;
