export const VendorPayAppsGridData = [
	{
		id: 1,
		payId: 'VPA10001',
		status: 'Draft',
		contract: 'Wing 1-5 Painting & Interiors',
		poNumber: '10001',
		companyName: 'Smartapp',
		invoiceAmount: 1000234,
		payappsAmount: 1000234,
		submittedDate: '2023-03-30T18:30:00Z',
	},
	{
		id: 2,
		payId: 'VPA10002',
		status: 'SubmittedWaitingForOtherParty',
		contract: 'Painting Contract',
		poNumber: '10002',
		companyName: 'Smartapp Comapny',
		invoiceAmount: 1000234,
		payappsAmount: 1000234,
		submittedDate: '2023-03-30T18:30:00Z',
	},
	{
		id: 3,
		payId: 'VPA10003',
		status: 'PaymentAuthorized',
		contract: 'Door Installation',
		poNumber: '10003',
		companyName: 'EIPSO Company',
		invoiceAmount: 32000,
		payappsAmount: 20009,
		submittedDate: '2023-06-30T18:30:00Z',
	},
	{
		id: 4,
		payId: 'VPA10004',
		status: 'AutoGeneratedWaitingForBothParties',
		contract: 'PaymentAuthorized',
		poNumber: '10004',
		companyName: 'American Company',
		invoiceAmount: 34567,
		payappsAmount: 120000,
		submittedDate: '2023-43-30T18:30:00Z',
	},
	{
		id: 5,
		payId: 'VPA10005',
		status: 'PaymentSent',
		contract: 'Excavation',
		poNumber: '10005',
		companyName: 'Florida Company',
		invoiceAmount: 23000,
		payappsAmount: 45000,
		submittedDate: '2023-07-30T18:30:00Z',
	},

	{
		id: 6,
		payId: 'VPA10006',
		status: 'PaymentReceived',
		contract: 'Column Casting',
		poNumber: '10006',
		companyName: 'Baltimore Paiting Services',
		invoiceAmount: 90000,
		payappsAmount: 300000,
		submittedDate: '2023-09-30T18:30:00Z',
	},
	{
		id: 7,
		payId: 'VPA10007',
		status: 'Draft',
		contract: 'Window Installation',
		poNumber: '10007',
		companyName: 'American Paiting Services',
		invoiceAmount: 80000,
		payappsAmount: 200000,
		submittedDate: '2023-11-30T18:30:00Z',
	},

];

export const vendorPayAppsGridData = {
	"data": [
		{
			"rowId": 1,
			"code": "VPA0010",
			"id": "df9e99e5-51f8-4380-812e-e2df5ea1140d",
			"poNumber": "P23456",
			"status": "PaymentSent",
			"submittedOn": "2023-06-22T18:07:41.963Z",
			"budgetAmount": 48000.00,
			"invoiceDate": "2023-06-22T18:07:41.963Z",
			"balanceAmount": 47000.00,
			"invoiceAmount": 1000.00,
			"retainagePercentage": 0,
			"retainageAmount": 0.00,
			"vendor": {
				"id": "82187766-1002-490b-860e-87496d4c01b4",
				"name": "1 Bid Company"
			},
			"amount": 1000.00,
			"contract": {
				"id": "953f6939-0fbe-4040-9805-62d9501683d2",
				"name": "Lights Installation"
			},
			"budgetItems": [
				{
					"bidValue": 432.00,
					"id": "836cccf9-973a-4ebb-81f7-d6f3d0a8aac5",
					"name": "00032",
					"costType": "L - Labor",
					"costCode": "Special Windows 8650",
					"division": "08 - Doors and Windows",
					"unitCost": 75.00,
					"unitOfMeasure": "Hours",
					"budgetAmount": 2000.00,
					"estimatedEndDate": "2023-06-30T00:00:00Z",
					"estimatedStartDate": "2023-05-19T00:00:00Z"
				},
				{
					"bidValue": 2000.00,
					"id": "836cccf9-973a-4ebb-81f7-d6f3d0a8aac5",
					"name": "00032",
					"costType": "L - Labor",
					"costCode": "Special Windows 8650",
					"division": "08 - Doors and Windows",
					"unitCost": 75.00,
					"unitOfMeasure": "Hours",
					"budgetAmount": 2000.00,
					"estimatedEndDate": "2023-06-30T00:00:00Z",
					"estimatedStartDate": "2023-05-19T00:00:00Z"
				},
				{
					"bidValue": 7000.00,
					"id": "836cccf9-973a-4ebb-81f7-d6f3d0a8aac5",
					"name": "00032",
					"costType": "L - Labor",
					"costCode": "Special Windows 8650",
					"division": "08 - Doors and Windows",
					"unitCost": 75.00,
					"unitOfMeasure": "Hours",
					"budgetAmount": 2000.00,
					"estimatedEndDate": "2023-06-30T00:00:00Z",
					"estimatedStartDate": "2023-05-19T00:00:00Z"
				},
				{
					"bidValue": 450000.00,
					"id": "836cccf9-973a-4ebb-81f7-d6f3d0a8aac5",
					"name": "00032",
					"costType": "L - Labor",
					"costCode": "Special Windows 8650",
					"division": "08 - Doors and Windows",
					"unitCost": 75.00,
					"unitOfMeasure": "Hours",
					"budgetAmount": 2000.00,
					"estimatedEndDate": "2023-06-30T00:00:00Z",
					"estimatedStartDate": "2023-05-19T00:00:00Z"
				},
				{
					"bidValue": 500000.00,
					"id": "836cccf9-973a-4ebb-81f7-d6f3d0a8aac5",
					"name": "00032",
					"costType": "L - Labor",
					"costCode": "Special Windows 8650",
					"division": "08 - Doors and Windows",
					"unitCost": 75.00,
					"unitOfMeasure": "Hours",
					"budgetAmount": 2000.00,
					"estimatedEndDate": "2023-06-30T00:00:00Z",
					"estimatedStartDate": "2023-05-19T00:00:00Z"
				},
				{
					"bidValue": 700000.00,
					"id": "836cccf9-973a-4ebb-81f7-d6f3d0a8aac5",
					"name": "00032",
					"costType": "L - Labor",
					"costCode": "Special Windows 8650",
					"division": "08 - Doors and Windows",
					"unitCost": 75.00,
					"unitOfMeasure": "Hours",
					"budgetAmount": 2000.00,
					"estimatedEndDate": "2023-06-30T00:00:00Z",
					"estimatedStartDate": "2023-05-19T00:00:00Z"
				},
				{
					"bidValue": 750000.00,
					"id": "836cccf9-973a-4ebb-81f7-d6f3d0a8aac5",
					"name": "00032",
					"costType": "L - Labor",
					"costCode": "Special Windows 8650",
					"division": "08 - Doors and Windows",
					"unitCost": 75.00,
					"unitOfMeasure": "Hours",
					"budgetAmount": 2000.00,
					"estimatedEndDate": "2023-06-30T00:00:00Z",
					"estimatedStartDate": "2023-05-19T00:00:00Z"
				},
				{
					"bidValue": 752000.00,
					"id": "836cccf9-973a-4ebb-81f7-d6f3d0a8aac5",
					"name": "00032",
					"costType": "L - Labor",
					"costCode": "Special Windows 8650",
					"division": "08 - Doors and Windows",
					"unitCost": 75.00,
					"unitOfMeasure": "Hours",
					"budgetAmount": 2000.00,
					"estimatedEndDate": "2023-06-30T00:00:00Z",
					"estimatedStartDate": "2023-05-19T00:00:00Z"
				},
				{
					"bidValue": 1000000.00,
					"id": "836cccf9-973a-4ebb-81f7-d6f3d0a8aac5",
					"name": "00032",
					"costType": "L - Labor",
					"costCode": "Special Windows 8650",
					"division": "08 - Doors and Windows",
					"unitCost": 75.00,
					"unitOfMeasure": "Hours",
					"budgetAmount": 2000.00,
					"estimatedEndDate": "2023-06-30T00:00:00Z",
					"estimatedStartDate": "2023-05-19T00:00:00Z"
				}
			]
		},
		{
			"rowId": 2,
			"code": "VPA0011",
			"id": "fb377f07-f0ad-45ca-94e7-08619627f0d5",
			"poNumber": "P23456",
			"status": "Draft",
			"submittedOn": "2023-06-23T06:46:22.977Z",
			"budgetAmount": 48000.00,
			"invoiceDate": "2023-06-23T06:46:22.977Z",
			"balanceAmount": 46400.00,
			"invoiceAmount": 1600.00,
			"retainagePercentage": 0,
			"retainageAmount": 0.00,
			"vendor": {
				"id": "82187766-1002-490b-860e-87496d4c01b4",
				"name": "1 Bid Company"
			},
			"amount": 1600.00,
			"contract": {
				"id": "953f6939-0fbe-4040-9805-62d9501683d2",
				"name": "Lights Installation"
			},
			"budgetItems": [
				{
					"bidValue": 1000.00,
					"id": "18904815-da8e-4e99-9645-4d1086dd8b98",
					"name": "00046",
					"costType": "E - Equipment",
					"costCode": "Access Flooring 10270",
					"division": "10 - Specialties",
					"unitCost": 100.00,
					"unitOfMeasure": "ea",
					"budgetAmount": 1000.00,
					"estimatedEndDate": "2023-06-16T00:00:00Z",
					"estimatedStartDate": "2023-06-13T00:00:00Z"
				},
				{
					"bidValue": 432.00,
					"id": "836cccf9-973a-4ebb-81f7-d6f3d0a8aac5",
					"name": "00032",
					"costType": "L - Labor",
					"costCode": "Special Windows 8650",
					"division": "08 - Doors and Windows",
					"unitCost": 75.00,
					"unitOfMeasure": "Hours",
					"budgetAmount": 2000.00,
					"estimatedEndDate": "2023-06-30T00:00:00Z",
					"estimatedStartDate": "2023-05-19T00:00:00Z"
				},
				{
					"bidValue": 2000.00,
					"id": "836cccf9-973a-4ebb-81f7-d6f3d0a8aac5",
					"name": "00032",
					"costType": "L - Labor",
					"costCode": "Special Windows 8650",
					"division": "08 - Doors and Windows",
					"unitCost": 75.00,
					"unitOfMeasure": "Hours",
					"budgetAmount": 2000.00,
					"estimatedEndDate": "2023-06-30T00:00:00Z",
					"estimatedStartDate": "2023-05-19T00:00:00Z"
				},
				{
					"bidValue": 7000.00,
					"id": "836cccf9-973a-4ebb-81f7-d6f3d0a8aac5",
					"name": "00032",
					"costType": "L - Labor",
					"costCode": "Special Windows 8650",
					"division": "08 - Doors and Windows",
					"unitCost": 75.00,
					"unitOfMeasure": "Hours",
					"budgetAmount": 2000.00,
					"estimatedEndDate": "2023-06-30T00:00:00Z",
					"estimatedStartDate": "2023-05-19T00:00:00Z"
				},
				{
					"bidValue": 450000.00,
					"id": "836cccf9-973a-4ebb-81f7-d6f3d0a8aac5",
					"name": "00032",
					"costType": "L - Labor",
					"costCode": "Special Windows 8650",
					"division": "08 - Doors and Windows",
					"unitCost": 75.00,
					"unitOfMeasure": "Hours",
					"budgetAmount": 2000.00,
					"estimatedEndDate": "2023-06-30T00:00:00Z",
					"estimatedStartDate": "2023-05-19T00:00:00Z"
				},
				{
					"bidValue": 500000.00,
					"id": "836cccf9-973a-4ebb-81f7-d6f3d0a8aac5",
					"name": "00032",
					"costType": "L - Labor",
					"costCode": "Special Windows 8650",
					"division": "08 - Doors and Windows",
					"unitCost": 75.00,
					"unitOfMeasure": "Hours",
					"budgetAmount": 2000.00,
					"estimatedEndDate": "2023-06-30T00:00:00Z",
					"estimatedStartDate": "2023-05-19T00:00:00Z"
				},
				{
					"bidValue": 700000.00,
					"id": "836cccf9-973a-4ebb-81f7-d6f3d0a8aac5",
					"name": "00032",
					"costType": "L - Labor",
					"costCode": "Special Windows 8650",
					"division": "08 - Doors and Windows",
					"unitCost": 75.00,
					"unitOfMeasure": "Hours",
					"budgetAmount": 2000.00,
					"estimatedEndDate": "2023-06-30T00:00:00Z",
					"estimatedStartDate": "2023-05-19T00:00:00Z"
				},
				{
					"bidValue": 750000.00,
					"id": "836cccf9-973a-4ebb-81f7-d6f3d0a8aac5",
					"name": "00032",
					"costType": "L - Labor",
					"costCode": "Special Windows 8650",
					"division": "08 - Doors and Windows",
					"unitCost": 75.00,
					"unitOfMeasure": "Hours",
					"budgetAmount": 2000.00,
					"estimatedEndDate": "2023-06-30T00:00:00Z",
					"estimatedStartDate": "2023-05-19T00:00:00Z"
				},
				{
					"bidValue": 752000.00,
					"id": "836cccf9-973a-4ebb-81f7-d6f3d0a8aac5",
					"name": "00032",
					"costType": "L - Labor",
					"costCode": "Special Windows 8650",
					"division": "08 - Doors and Windows",
					"unitCost": 75.00,
					"unitOfMeasure": "Hours",
					"budgetAmount": 2000.00,
					"estimatedEndDate": "2023-06-30T00:00:00Z",
					"estimatedStartDate": "2023-05-19T00:00:00Z"
				},
				{
					"bidValue": 1000000.00,
					"id": "836cccf9-973a-4ebb-81f7-d6f3d0a8aac5",
					"name": "00032",
					"costType": "L - Labor",
					"costCode": "Special Windows 8650",
					"division": "08 - Doors and Windows",
					"unitCost": 75.00,
					"unitOfMeasure": "Hours",
					"budgetAmount": 2000.00,
					"estimatedEndDate": "2023-06-30T00:00:00Z",
					"estimatedStartDate": "2023-05-19T00:00:00Z"
				}
			]
		},
		{
			"rowId": 3,
			"code": "VPA0012",
			"id": "ef125fff-b32f-401f-a75d-760205fb9fc5",
			"poNumber": "P100011",
			"status": "AutoGeneratedWaitingForBothParties",
			"submittedOn": "2023-06-29T10:41:10.013Z",
			"budgetAmount": 7000.00,
			"invoiceDate": "2023-06-29T10:41:10.013Z",
			"balanceAmount": 2000.00,
			"invoiceAmount": 5000.00,
			"retainagePercentage": 10,
			"retainageAmount": null,
			"vendor": {
				"id": "82187766-1002-490b-860e-87496d4c01b4",
				"name": "1 Bid Company"
			},
			"amount": 5000.00,
			"contract": {
				"id": "7d01c1ef-e603-473c-9d92-6368e31aebde",
				"name": "Plants Installation"
			},
			"budgetItems": []
		},
		{
			"rowId": 5,
			"code": "VPA0013",
			"id": "003b1155-b933-465c-8523-6217d6c4b7f8",
			"poNumber": "P100011",
			"status": "PaymentSent",
			"submittedOn": "2023-06-29T11:07:33.957Z",
			"budgetAmount": 7000.00,
			"invoiceDate": "2023-06-29T11:07:33.957Z",
			"balanceAmount": 3900.00,
			"invoiceAmount": 3100.00,
			"retainagePercentage": 10,
			"retainageAmount": 40.00,
			"vendor": {
				"id": "82187766-1002-490b-860e-87496d4c01b4",
				"name": "1 Bid Company"
			},
			"amount": 3100.00,
			"contract": {
				"id": "7d01c1ef-e603-473c-9d92-6368e31aebde",
				"name": "Plants Installation"
			},
			"budgetItems": [
				{
					"bidValue": 3000.00,
					"id": "d97e41aa-9731-464e-9083-2e67f4b1ec41",
					"name": "00050",
					"quantity": null,
					"costType": "SVC - Professional Services",
					"costCode": "General Contractor- Facilities Manager 1017",
					"division": "01 - General Requirement",
					"unitCost": 50000.00,
					"unitOfMeasure": "Months",
					"budgetAmount": 3000.00,
					"estimatedEndDate": "2023-07-31T00:00:00Z",
					"estimatedStartDate": "2023-06-28T00:00:00Z"
				},
				{
					"bidValue": 3500.00,
					"id": "82aa9533-66cd-4586-8535-636c1043cd31",
					"name": "00011",
					"quantity": null,
					"costType": "E - Equipment",
					"costCode": "General Contractor- Airports 1002",
					"division": "01 - General Requirement",
					"unitCost": null,
					"unitOfMeasure": "",
					"budgetAmount": 4000.00,
					"estimatedEndDate": "2023-03-10T00:00:00Z",
					"estimatedStartDate": "2023-03-10T00:00:00Z"
				},
				{
					"bidValue": 4000.00,
					"id": "82aa9533-66cd-4586-8535-636c1043cd31",
					"name": "00011",
					"quantity": null,
					"costType": "E - Equipment",
					"costCode": "General Contractor- Airports 1002",
					"division": "01 - General Requirement",
					"unitCost": null,
					"unitOfMeasure": "",
					"budgetAmount": 4000.00,
					"estimatedEndDate": "2023-03-10T00:00:00Z",
					"estimatedStartDate": "2023-03-10T00:00:00Z"
				}
			]
		},
		{
			"rowId": 6,
			"code": "VPA0014",
			"id": "166fb354-bd93-429e-9c0b-1fc55997e282",
			"poNumber": null,
			"status": "PaymentReceived",
			"submittedOn": "2023-06-30T11:37:38.52Z",
			"budgetAmount": 68500.00,
			"invoiceDate": "2023-06-30T11:37:38.52Z",
			"balanceAmount": 57100.00,
			"invoiceAmount": 11400.00,
			"retainagePercentage": 0,
			"retainageAmount": 0.00,
			"vendor": {
				"id": "82187766-1002-490b-860e-87496d4c01b4",
				"name": "1 Bid Company"
			},
			"amount": 11400.00,
			"contract": {
				"id": "636acdb9-6256-4566-b1bd-d33795c8f795",
				"name": "Test 30-06-23"
			},
			"budgetItems": [
				{
					"bidValue": 3500.00,
					"id": "a694d471-888d-4500-8274-2cecf1b0ea3a",
					"name": "00055",
					"quantity": null,
					"costType": "S - Commitment",
					"costCode": "Precast Concrete 3400",
					"division": "03 - Concrete",
					"unitCost": 1000.00,
					"unitOfMeasure": "cc",
					"budgetAmount": 3500.00,
					"estimatedEndDate": "2023-07-31T00:00:00Z",
					"estimatedStartDate": "2023-06-30T00:00:00Z"
				},
				{
					"bidValue": 25000.00,
					"id": "ebaeb41f-211b-4d3f-9c8b-88b851b4f371",
					"name": "00053",
					"quantity": null,
					"costType": "M - Materials",
					"costCode": "Concrete Contractor 3010",
					"division": "03 - Concrete",
					"unitCost": 1000.00,
					"unitOfMeasure": "m3",
					"budgetAmount": 25000.00,
					"estimatedEndDate": "2023-07-31T00:00:00Z",
					"estimatedStartDate": "2023-06-30T00:00:00Z"
				}
			]
		},
		{
			"rowId": 7,
			"code": "VPA0015",
			"id": "9366cc8c-cfaa-42f6-9746-92bd883ce566",
			"poNumber": "P34567",
			"status": "PaymentSent",
			"submittedOn": "2023-06-30T16:30:44.507Z",
			"budgetAmount": 5011500.00,
			"invoiceDate": "2023-06-30T16:30:44.507Z",
			"balanceAmount": 3509500.00,
			"invoiceAmount": 1502000.00,
			"retainagePercentage": 0,
			"retainageAmount": 0.00,
			"vendor": {
				"id": "4dec6c09-da4b-4cd4-9f45-cb054418b362",
				"name": "IQ Vendor"
			},
			"amount": 1502000.00,
			"contract": {
				"id": "d4fc52c8-22c1-4b13-86ce-133b7bb459df",
				"name": "30-06-23 Bid 1"
			},
			"budgetItems": [
				{
					"bidValue": 5000000.00,
					"id": "da1bb9ee-fe88-4b76-831c-3c004e03bf09",
					"name": "00060",
					"quantity": null,
					"costType": "M - Materials",
					"costCode": "Lumber 6300",
					"division": "06 - Wood and Plastics",
					"unitCost": 50.00,
					"unitOfMeasure": "m2",
					"budgetAmount": 5000000.00,
					"estimatedEndDate": "2023-07-31T00:00:00Z",
					"estimatedStartDate": "2023-06-30T00:00:00Z"
				},
				{
					"bidValue": 4000.00,
					"id": "7ddc436c-2536-47b7-a36a-d5cdbacb6589",
					"name": "00062",
					"quantity": null,
					"costType": "E - Equipment",
					"costCode": "Plastic Fabrications 6600",
					"division": "06 - Wood and Plastics",
					"unitCost": 1000.00,
					"unitOfMeasure": "ea",
					"budgetAmount": 4000.00,
					"estimatedEndDate": "2023-07-31T00:00:00Z",
					"estimatedStartDate": "2023-06-30T00:00:00Z"
				}
			]
		},
		{
			"rowId": 8,
			"code": "VPA0016",
			"id": "11c7144f-d05b-4782-b7a7-5e350eeafe70",
			"poNumber": "P34567",
			"status": "PaymentReceived",
			"submittedOn": "2023-06-30T19:04:01.593Z",
			"budgetAmount": 5011500.00,
			"invoiceDate": "2023-06-30T19:04:01.593Z",
			"balanceAmount": 4011500.00,
			"invoiceAmount": 1000000.00,
			"retainagePercentage": 0,
			"retainageAmount": 0.00,
			"vendor": {
				"id": "4dec6c09-da4b-4cd4-9f45-cb054418b362",
				"name": "IQ Vendor"
			},
			"amount": 1000000.00,
			"contract": {
				"id": "d4fc52c8-22c1-4b13-86ce-133b7bb459df",
				"name": "30-06-23 Bid 1"
			},
			"budgetItems": [
				{
					"bidValue": 5000000.00,
					"id": "da1bb9ee-fe88-4b76-831c-3c004e03bf09",
					"name": "00060",
					"quantity": null,
					"costType": "M - Materials",
					"costCode": "Lumber 6300",
					"division": "06 - Wood and Plastics",
					"unitCost": 50.00,
					"unitOfMeasure": "m2",
					"budgetAmount": 5000000.00,
					"estimatedEndDate": "2023-07-31T00:00:00Z",
					"estimatedStartDate": "2023-06-30T00:00:00Z"
				}
			]
		},
		{
			"rowId": 9,
			"code": "VPA0004",
			"id": "d46d6bce-9512-4074-8c24-fb0aee51ead6",
			"poNumber": null,
			"status": "PaymentAuthorized",
			"submittedOn": "2023-08-18T09:45:07.207Z",
			"budgetAmount": 150000,
			"invoiceDate": "2023-08-18T09:45:07.207Z",
			"balanceAmount": 101000,
			"invoiceAmount": 49000,
			"retainagePercentage": 0,
			"retainageAmount": 0,
			"vendor": {
				"id": "952033a3-1f05-4fed-9d32-5ef792a18003",
				"name": "Sub Contractor Company"
			},
			"amount": 49000,
			"contract": {
				"id": "d0a34286-6f5f-42e6-a702-e97eab14c413",
				"name": "Design Heavy"
			},
			"budgetItems": [
				{
					"bidValue": 70000,
					"budgetAmount": 70000,
					"name": "00004",
					"id": "bf666941-5b72-408b-8bb6-bab66904546e",
					"quantity": null,
					"costType": "E - Equipment",
					"costCode": "General Contractor- Design/Build 1005",
					"division": "01 - General Requirement",
					"unitCost": 70,
					"description": null,
					"unitOfMeasure": "m2",
					"estimatedEndDate": "2023-08-25T00:00:00Z",
					"estimatedStartDate": "2023-08-18T00:00:00Z"
				}
			]
		},
	]
};